const EQUIPMENT_QUOTE_KEY='equipment_quotes_v1';
let equipmentQuoteData=JSON.parse(localStorage.getItem(EQUIPMENT_QUOTE_KEY)||'null')||{categories:['衛浴','燈具','廚具','家電','五金','其他'],vendors:[],items:[]};
function equipmentQuoteSave(){localStorage.setItem(EQUIPMENT_QUOTE_KEY,JSON.stringify(equipmentQuoteData));}
function equipmentQuoteId(prefix){return prefix+'_'+Date.now()+'_'+Math.random().toString(36).slice(2);}
function equipmentCategories(){return [...new Set((equipmentQuoteData.categories||[]).map(x=>String(x).trim()).filter(Boolean))];}
function equipmentVendor(id){return equipmentQuoteData.vendors.find(v=>v.id===id);}
function equipmentQuoteHome(){
  main.innerHTML='<button class="back" onclick="quoteHome()">← 報價管理</button><div class="section"><div><b>設備報價</b><div class="muted">設備分類、獨立廠商與多家報價比較。</div></div><button class="light" onclick="newEquipmentCategory()">＋ 新增分類</button></div>'+equipmentCategories().map(category=>'<div class="card" style="cursor:pointer;display:flex;justify-content:space-between;align-items:center" onclick="equipmentQuoteCategory(\''+esc(category)+'\')"><div><h3 style="margin:0 0 5px">'+esc(category)+'</h3><div class="muted">'+equipmentQuoteData.items.filter(item=>item.category===category).length+' 個設備　｜　'+equipmentQuoteData.vendors.filter(v=>v.category===category).length+' 家設備廠商</div></div><b style="font-size:22px">→</b></div>').join('');
}
function newEquipmentCategory(){openModal('<h2>新增設備分類</h2><label>分類名稱<input id="equipmentCategoryName" placeholder="例如：衛浴"></label><div class="actions"><button class="light" onclick="closeModal()">取消</button><button onclick="saveEquipmentCategory()">儲存</button></div>');}
function saveEquipmentCategory(){const name=document.getElementById('equipmentCategoryName').value.trim();if(!name){alert('請輸入分類名稱。');return;}if(equipmentCategories().includes(name)){alert('此分類已存在。');return;}equipmentQuoteData.categories.push(name);equipmentQuoteSave();closeModal();equipmentQuoteHome();}
function equipmentQuoteCategory(category){
  const items=equipmentQuoteData.items.filter(item=>item.category===category);
  main.innerHTML='<button class="back" onclick="equipmentQuoteHome()">← 設備報價</button><div class="section"><div><b>'+esc(category)+'</b><div class="muted">設備項目與廠商報價比較。</div></div><div><button class="light" onclick="equipmentVendors(\''+esc(category)+'\')">設備廠商</button> <button onclick="editEquipmentItem(\''+esc(category)+'\')">＋ 新增設備</button></div></div>'+(items.length?items.map(item=>equipmentItemHTML(item)).join(''):'<div class="empty">尚無設備項目。<br><br><button onclick="editEquipmentItem(\''+esc(category)+'\')">＋ 新增第一筆設備</button></div>');
}
function equipmentItemHTML(item){
  const quotes=(item.quotes||[]),lowest=quotes.filter(q=>Number.isFinite(Number(q.unitPrice))).sort((a,b)=>Number(a.unitPrice)-Number(b.unitPrice))[0];
  const quoteRows=quotes.length?quotes.map(quote=>{const vendor=equipmentVendor(quote.vendorId);return '<div class="row" style="padding:7px 0"><div style="flex:1"><b>'+esc(vendor?.name||'已刪除廠商')+'</b><div class="muted">'+esc(quote.date||'未填日期')+'　｜　'+Number(quote.unitPrice||0).toLocaleString()+' × '+Number(quote.qty||item.qty||1)+' = '+Number(quote.total||0).toLocaleString()+(lowest?.id===quote.id?'　最低價':'')+'</div></div><button class="light" onclick="editEquipmentQuote(\''+esc(item.id)+'\',\''+esc(quote.id)+'\')">編輯</button></div>';}).join(''):'<div class="muted" style="margin:8px 0">尚無廠商報價。</div>';
  return '<div class="card"><div class="row"><div style="flex:1"><b>'+esc(item.name)+'</b><div class="muted">'+esc(item.model||'未填品牌／型號')+'　｜　數量 '+Number(item.qty||1)+'</div></div><button class="light" onclick="editEquipmentItem(\''+esc(item.category)+'\',\''+esc(item.id)+'\')">編輯</button></div><div style="margin:8px 0">'+quoteRows+'</div><button class="light" onclick="editEquipmentQuote(\''+esc(item.id)+'\')">＋ 新增廠商報價</button></div>';
}
function editEquipmentItem(category,id=''){const item=equipmentQuoteData.items.find(item=>item.id===id)||{};openModal('<h2>'+ (id?'編輯設備':'新增設備')+'</h2><label>設備名稱<input id="equipmentItemName" value="'+esc(item.name||'')+'"></label><label>品牌／型號<input id="equipmentItemModel" value="'+esc(item.model||'')+'"></label><label>數量<input id="equipmentItemQty" type="number" min="1" value="'+esc(String(item.qty||1))+'"></label><label>備註<textarea id="equipmentItemNote">'+esc(item.note||'')+'</textarea></label><div class="actions">'+(id?'<button class="danger" onclick="deleteEquipmentItem(\''+esc(id)+'\')">刪除設備</button>':'')+'<button class="light" onclick="closeModal()">取消</button><button onclick="saveEquipmentItem(\''+esc(category)+'\',\''+esc(id)+'\')">儲存</button></div>');}
function saveEquipmentItem(category,id){const name=document.getElementById('equipmentItemName').value.trim(),qty=Number(document.getElementById('equipmentItemQty').value);if(!name||!Number.isFinite(qty)||qty<1){alert('請輸入設備名稱與有效數量。');return;}const item={id:id||equipmentQuoteId('item'),category,name,model:document.getElementById('equipmentItemModel').value.trim(),qty,note:document.getElementById('equipmentItemNote').value,quotes:id?(equipmentQuoteData.items.find(row=>row.id===id)?.quotes||[]):[]};const index=equipmentQuoteData.items.findIndex(row=>row.id===id);if(index>=0)equipmentQuoteData.items[index]=item;else equipmentQuoteData.items.push(item);equipmentQuoteSave();closeModal();equipmentQuoteCategory(category);}
function deleteEquipmentItem(id){const item=equipmentQuoteData.items.find(row=>row.id===id);if(!item||!confirm('確定刪除此設備及其報價？'))return;equipmentQuoteData.items=equipmentQuoteData.items.filter(row=>row.id!==id);equipmentQuoteSave();closeModal();equipmentQuoteCategory(item.category);}
function equipmentVendors(category){const vendors=equipmentQuoteData.vendors.filter(v=>v.category===category);openModal('<h2>'+esc(category)+'｜設備廠商</h2><div>'+ (vendors.map(v=>'<div class="row"><b style="flex:1">'+esc(v.name)+'</b><button class="light" onclick="editEquipmentVendor(\''+esc(category)+'\',\''+esc(v.id)+'\')">編輯</button><button class="light" onclick="deleteEquipmentVendor(\''+esc(category)+'\',\''+esc(v.id)+'\')">刪除</button></div>').join('')||'<p class="muted">尚無設備廠商。</p>')+'</div><div class="actions"><button class="light" onclick="closeModal()">完成</button><button onclick="editEquipmentVendor(\''+esc(category)+'\')">＋ 新增廠商</button></div>');}
function editEquipmentVendor(category,id=''){const vendor=equipmentVendor(id)||{};openModal('<h2>'+ (id?'編輯設備廠商':'新增設備廠商')+'</h2><label>廠商名稱<input id="equipmentVendorName" value="'+esc(vendor.name||'')+'"></label><div class="actions"><button class="light" onclick="equipmentVendors(\''+esc(category)+'\')">取消</button><button onclick="saveEquipmentVendor(\''+esc(category)+'\',\''+esc(id)+'\')">儲存</button></div>');}
function saveEquipmentVendor(category,id){const name=document.getElementById('equipmentVendorName').value.trim();if(!name){alert('請輸入廠商名稱。');return;}if(equipmentQuoteData.vendors.some(v=>v.category===category&&v.name===name&&v.id!==id)){alert('此分類已有同名廠商。');return;}const vendor={id:id||equipmentQuoteId('vendor'),category,name};const index=equipmentQuoteData.vendors.findIndex(v=>v.id===id);if(index>=0)equipmentQuoteData.vendors[index]=vendor;else equipmentQuoteData.vendors.push(vendor);equipmentQuoteSave();equipmentVendors(category);}
function deleteEquipmentVendor(category,id){if(!confirm('確定刪除這家設備廠商及其比較報價？'))return;equipmentQuoteData.vendors=equipmentQuoteData.vendors.filter(v=>v.id!==id);equipmentQuoteData.items.forEach(item=>item.quotes=(item.quotes||[]).filter(quote=>quote.vendorId!==id));equipmentQuoteSave();equipmentVendors(category);}
function editEquipmentQuote(itemId,quoteId=''){const item=equipmentQuoteData.items.find(row=>row.id===itemId);if(!item)return;const quote=(item.quotes||[]).find(row=>row.id===quoteId)||{},vendors=equipmentQuoteData.vendors.filter(v=>v.category===item.category);openModal('<h2>'+esc(item.name)+'｜'+(quoteId?'編輯廠商報價':'新增廠商報價')+'</h2>'+(vendors.length?'<label>廠商<select id="equipmentQuoteVendor">'+vendors.map(v=>'<option value="'+esc(v.id)+'" '+(v.id===quote.vendorId?'selected':'')+'>'+esc(v.name)+'</option>').join('')+'</select></label>':'<p class="muted">請先新增設備廠商。</p>')+'<label>報價日期<input id="equipmentQuoteDate" type="date" value="'+esc(quote.date||localDateISO(new Date()))+'"></label><label>單價<input id="equipmentQuotePrice" type="number" min="0" value="'+esc(String(quote.unitPrice??''))+'"></label><label>數量<input id="equipmentQuoteQty" type="number" min="1" value="'+esc(String(quote.qty||item.qty||1))+'"></label><label>備註<textarea id="equipmentQuoteNote">'+esc(quote.note||'')+'</textarea></label><div class="actions">'+(quoteId?'<button class="danger" onclick="deleteEquipmentQuote(\''+esc(item.id)+'\',\''+esc(quoteId)+'\')">刪除報價</button>':'')+'<button class="light" onclick="equipmentQuoteCategory(\''+esc(item.category)+'\')">取消</button><button '+(vendors.length?'':'disabled')+' onclick="saveEquipmentQuote(\''+esc(item.id)+'\',\''+esc(quoteId)+'\')">儲存</button></div>');}
function saveEquipmentQuote(itemId,quoteId){const item=equipmentQuoteData.items.find(row=>row.id===itemId);if(!item)return;const unitPrice=Number(document.getElementById('equipmentQuotePrice').value),qty=Number(document.getElementById('equipmentQuoteQty').value);if(!Number.isFinite(unitPrice)||unitPrice<0||!Number.isFinite(qty)||qty<1){alert('請輸入有效單價與數量。');return;}const quote={id:quoteId||equipmentQuoteId('quote'),vendorId:document.getElementById('equipmentQuoteVendor').value,date:document.getElementById('equipmentQuoteDate').value,unitPrice,qty,total:unitPrice*qty,note:document.getElementById('equipmentQuoteNote').value};item.quotes||=[];const index=item.quotes.findIndex(row=>row.id===quoteId);if(index>=0)item.quotes[index]=quote;else item.quotes.push(quote);equipmentQuoteSave();closeModal();equipmentQuoteCategory(item.category);}
function deleteEquipmentQuote(itemId,quoteId){const item=equipmentQuoteData.items.find(row=>row.id===itemId);if(!item||!confirm('確定刪除此廠商報價？'))return;item.quotes=item.quotes.filter(row=>row.id!==quoteId);equipmentQuoteSave();closeModal();equipmentQuoteCategory(item.category);}
const originalQuoteHome=quoteHome;
quoteHome=function(){
  originalQuoteHome();
  const anchor=main.querySelector('.hint');
  const entry='<div class="section"><div><b>設備報價</b><div class="muted">獨立管理設備分類、設備廠商與多家比較報價。</div></div><button class="light" onclick="equipmentQuoteHome()">開啟設備報價</button></div>';
  if(anchor)anchor.insertAdjacentHTML('beforebegin',entry);else main.insertAdjacentHTML('beforeend',entry);
};
