function projectRecord(id){return data.projects.find(project=>String(project.id)===String(id));}
function projectReferences(project){if(!project.projectReferences||typeof project.projectReferences!=='object')project.projectReferences={ownerQuote:{},costQuote:{},documents:[]};if(!Array.isArray(project.projectReferences.documents))project.projectReferences.documents=[];return project.projectReferences;}
function openProjectData(id){
  const p=projectRecord(id);if(!p)return;const refs=projectReferences(p),docs=refs.documents||[];
  main.innerHTML='<button class="back" onclick="openProject('+id+')">← 返回工程</button><div class="card"><span class="tag">專案資料</span><h2>'+esc(p.name)+'</h2><div class="muted">集中管理此工程的基本資料、進度、報價與文件。</div></div><div class="section"><b>基本資料</b><button class="light" onclick="openProjectBasicData('+id+')">查看／編輯</button></div><div class="card"><div class="muted">'+esc(p.client||'未設定業主')+'　｜　預估開工 '+esc(fmtDate(p.scheduleMeta?.estimatedStart||''))+'</div></div><div class="section"><b>工進表</b><button class="light" onclick="openProjectSchedule('+id+',\'main\')">開啟</button></div><div class="section"><b>業主報價單</b><button class="light" onclick="openProjectReference('+id+',\'ownerQuote\')">查看／編輯</button></div><div class="card"><div class="muted">'+esc(refs.ownerQuote?.title||'尚未設定')+'</div></div><div class="section"><b>工程成本／廠商報價</b><button class="light" onclick="openProjectReference('+id+',\'costQuote\')">查看／編輯</button></div><div class="card"><div class="muted">'+esc(refs.costQuote?.title||'尚未設定')+'</div></div><div class="section"><b>工程文件</b><button class="light" onclick="openProjectDocumentEditor('+id+')">＋ 新增文件</button></div><div class="card">'+(docs.map(doc=>'<div class="row"><div style="flex:1"><b>'+esc(doc.name)+'</b><div class="muted">'+esc(doc.note||doc.url||'')+'</div></div><button class="light" onclick="openProjectDocumentEditor('+id+',\''+esc(doc.id)+'\')">編輯</button></div>').join('')||'<div class="muted">尚未新增工程文件。</div>')+'</div>';
}
function openProjectBasicData(id){
  const p=projectRecord(id);if(!p)return;const meta=p.scheduleMeta||{};
  main.innerHTML='<button class="back" onclick="openProjectData('+id+')">← 專案資料</button><div class="card"><h2>基本資料</h2><label>工程名稱<input id="projectBasicName" value="'+esc(p.name)+'"></label><label>業主／公司<input id="projectBasicClient" value="'+esc(p.client||'')+'"></label><div class="grid"><label>預估開工日期<input id="projectBasicStart" type="date" value="'+esc(meta.estimatedStart||'')+'"></label><label>預估工期（日曆天）<input id="projectBasicDuration" type="number" min="1" value="'+esc(String(meta.estimatedDuration||''))+'"></label></div><div class="actions"><button class="light" onclick="openProjectData('+id+')">取消</button><button onclick="saveProjectBasicData('+id+')">儲存</button></div></div><div class="section"><b>刪除此工程</b></div><div class="card"><p class="muted">會刪除目前工程與其工程日報、現場問題資料；不會影響其他工程、報價或工種庫。</p><div class="actions"><button class="danger" style="width:100%" onclick="requestDeleteProject('+id+')">刪除此工程</button></div></div>';
}
function saveProjectBasicData(id){const p=projectRecord(id);if(!p)return;const name=document.getElementById('projectBasicName').value.trim(),client=document.getElementById('projectBasicClient').value.trim(),start=document.getElementById('projectBasicStart').value,duration=Number(document.getElementById('projectBasicDuration').value);if(!name||!isCompleteScheduleDate(start)||!Number.isFinite(duration)||duration<1){alert('請填寫工程名稱、預估開工日期與預估工期。');return;}p.name=name;p.client=client||'未設定';p.scheduleMeta={...(p.scheduleMeta||{}),estimatedStart:start,estimatedDuration:Math.floor(duration)};save();openProjectBasicData(id);}
function openProjectReference(id,type){const p=projectRecord(id);if(!p)return;const refs=projectReferences(p),record=refs[type]||{},title=type==='ownerQuote'?'業主報價單':'工程成本／廠商報價';main.innerHTML='<button class="back" onclick="openProjectData('+id+')">← 專案資料</button><div class="card"><h2>'+title+'</h2><label>名稱<input id="projectReferenceTitle" value="'+esc(record.title||'')+'"></label><label>連結／位置<input id="projectReferenceUrl" value="'+esc(record.url||'')+'" placeholder="可貼上雲端檔案連結"></label><label>備註<textarea id="projectReferenceNote">'+esc(record.note||'')+'</textarea></label><div class="actions"><button class="light" onclick="quoteGate()">開啟既有報價管理</button><button onclick="saveProjectReference('+id+',\''+type+'\')">儲存</button></div></div>';}
function saveProjectReference(id,type){const p=projectRecord(id);if(!p)return;const refs=projectReferences(p);refs[type]={title:document.getElementById('projectReferenceTitle').value.trim(),url:document.getElementById('projectReferenceUrl').value.trim(),note:document.getElementById('projectReferenceNote').value};save();openProjectData(id);}
function openProjectDocumentEditor(id,documentId=''){const p=projectRecord(id);if(!p)return;const refs=projectReferences(p),doc=refs.documents.find(item=>item.id===documentId)||{};openModal('<h2>'+ (documentId?'編輯工程文件':'新增工程文件')+'</h2><label>文件名稱<input id="projectDocumentName" value="'+esc(doc.name||'')+'"></label><label>連結／位置<input id="projectDocumentUrl" value="'+esc(doc.url||'')+'" placeholder="可貼上雲端檔案連結"></label><label>備註<textarea id="projectDocumentNote">'+esc(doc.note||'')+'</textarea></label><div class="actions">'+(documentId?'<button class="danger" onclick="deleteProjectDocument('+id+',\''+esc(documentId)+'\')">刪除</button>':'')+'<button class="light" onclick="closeModal()">取消</button><button onclick="saveProjectDocument('+id+',\''+esc(documentId)+'\')">儲存</button></div>');}
function saveProjectDocument(id,documentId){const p=projectRecord(id);if(!p)return;const name=document.getElementById('projectDocumentName').value.trim();if(!name){alert('請輸入文件名稱。');return;}const refs=projectReferences(p),doc={id:documentId||'doc:'+Date.now(),name,url:document.getElementById('projectDocumentUrl').value.trim(),note:document.getElementById('projectDocumentNote').value};const index=refs.documents.findIndex(item=>item.id===documentId);if(index>=0)refs.documents[index]=doc;else refs.documents.push(doc);save();closeModal();openProjectData(id);}
function deleteProjectDocument(id,documentId){const p=projectRecord(id);if(!p||!confirm('確定刪除此文件記錄？'))return;projectReferences(p).documents=projectReferences(p).documents.filter(item=>item.id!==documentId);save();closeModal();openProjectData(id);}
function requestDeleteProject(id){const p=projectRecord(id);if(!p)return;openModal('<h2>刪除工程</h2><p class="muted">此操作只會刪除「'+esc(p.name)+'」。請先輸入目前系統的管理密碼。</p><label>管理密碼<input id="deleteProjectPassword" type="password" autocomplete="current-password"></label><div class="actions"><button class="light" onclick="closeModal()">取消</button><button class="danger" onclick="confirmDeleteProjectPassword('+id+')">下一步</button></div>');}
function confirmDeleteProjectPassword(id){if(document.getElementById('deleteProjectPassword').value!==PROJECT_DELETE_PASSWORD){alert('密碼錯誤。');return;}const p=projectRecord(id);if(!p)return;openModal('<h2>再次確認刪除</h2><p>確定要永久刪除「'+esc(p.name)+'」嗎？</p><label><input id="deleteProjectFinal" type="checkbox"> 我確認只刪除此工程</label><div class="actions"><button class="light" onclick="closeModal()">取消</button><button class="danger" onclick="deleteCurrentProject('+id+')">永久刪除</button></div>');}
function deleteCurrentProject(id){if(!document.getElementById('deleteProjectFinal')?.checked){alert('請先勾選確認。');return;}const project=projectRecord(id);if(!project)return;data.projects=data.projects.filter(item=>String(item.id)!==String(id));if(Array.isArray(data.issues))data.issues=data.issues.filter(issue=>String(issue.projectId)!==String(id));if(Array.isArray(data.dailyReports))data.dailyReports=data.dailyReports.filter(report=>String(report.projectId)!==String(id));save();closeModal();projects();}
