function methods(e){nav(e);main.innerHTML='<div class="section"><b>工法／材料資料庫</b><button onclick="newMethod()">＋ 新增</button></div><div class="hint">可依品牌、系列、型號、用途搜尋。資料會直接保存在目前工程資料庫，不會另外建立新資料庫。</div><input id="methodSearch" placeholder="搜尋：神保、Panasonic、G系列、星光、面板…" oninput="renderMethods()"><div id="methodList"></div>';renderMethods()}

function renderMethods(){let box=document.getElementById('methodList');if(!box)return;let q=(document.getElementById('methodSearch').value||'').toLowerCase();let list=(data.methods||[]).filter(x=>(x.name+' '+x.maker+' '+x.series+' '+x.model+' '+x.category).toLowerCase().includes(q));box.innerHTML=list.map((m,i)=>'<div class="card"><span class="tag">'+esc(m.category)+'</span><h3 style="margin:8px 0 5px">'+esc(m.name)+'</h3><div class="muted">'+esc(m.maker)+'　'+esc(m.series)+'　'+esc(m.model)+'</div><p style="margin:10px 0">'+esc(m.note)+'</p><b>'+esc(m.price||'未設定')+'</b><div class="muted">'+esc(m.priceNote||'參考價格')+'</div><div style="margin-top:10px"><button class="light" onclick="editMethod('+i+')">編輯</button> <button onclick="deleteMethod('+i+')">刪除</button>'+(m.url?'<button class="light" onclick="window.open(\''+m.url+'\',\'_blank\')">查最新價格</button>':'')+'</div></div>').join('')||'<div class="empty">找不到資料。</div>'}

function newMethod(){openModal('<h2>新增工法／材料</h2><label>分類</label><select id="mc"><option>水電</option><option>泥作</option><option>木作</option><option>油漆</option><option>設備</option><option>其他</option></select><label>名稱</label><input id="mn" placeholder="例如：面板／貼磚工法"><label>品牌</label><input id="mm" placeholder="例如：神保電器"><label>系列</label><input id="ms" placeholder="例如：NK系列"><label>型號</label><input id="mmo"><label>參考單價</label><input id="mp" placeholder="例如：¥1,870（税込）"><label>價格備註</label><input id="mpn" placeholder="例如：2026/09、含稅／未稅"><label>說明</label><textarea id="mnote"></textarea><label>查價網址（可選）</label><input id="murl" placeholder="官方產品頁／供應商頁"><div class="actions"><button class="light" onclick="closeModal()">取消</button><button onclick="saveMethod()">儲存</button></div>')}

function saveMethod(){if(!mn.value)return;(data.methods||=[]).push({category:mc.value,name:mn.value,maker:mm.value,series:ms.value,model:mmo.value,price:mp.value,priceNote:mpn.value,note:mnote.value,url:murl.value});save();closeModal();methods()}

function editMethod(i){let m=data.methods[i];openModal('<h2>編輯工法／材料</h2><label>分類</label><input id="mc" value="'+esc(m.category)+'"><label>名稱</label><input id="mn" value="'+esc(m.name)+'"><label>品牌</label><input id="mm" value="'+esc(m.maker)+'"><label>系列</label><input id="ms" value="'+esc(m.series)+'"><label>型號</label><input id="mmo" value="'+esc(m.model)+'"><label>參考單價</label><input id="mp" value="'+esc(m.price)+'"><label>價格備註</label><input id="mpn" value="'+esc(m.priceNote)+'"><label>說明</label><textarea id="mnote">'+esc(m.note)+'</textarea><label>查價網址（可選）</label><input id="murl" value="'+esc(m.url||'')+'"><div class="actions"><button class="light" onclick="closeModal()">取消</button><button onclick="updateMethod('+i+')">儲存</button></div>')}

function updateMethod(i){let m=data.methods[i];m.category=mc.value;m.name=mn.value;m.maker=mm.value;m.series=ms.value;m.model=mmo.value;m.price=mp.value;m.priceNote=mpn.value;m.note=mnote.value;m.url=murl.value;save();closeModal();methods()}

function deleteMethod(i){if(confirm('刪除此資料？')){data.methods.splice(i,1);save();methods()}}
